name: "Deploy website"

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          cd website
          npm i
          npm run build

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages
          FOLDER: website/public